"""Shim directory of per-tool commands, so VICAR tools run unqualified.

``tig marsmap ...`` always works, but existing pipelines and muscle memory
expect ``marsmap ...``. A shim directory holds one symlink per VICAR tool
pointing at a single dispatcher script, which re-invokes ``tig`` with the name
it was called as.
"""
import os
import shlex
import shutil
import stat
import sys
from pathlib import Path
from typing import Iterable, List, Tuple

DISPATCHER_NAME = "tig-shim"

DISPATCHER_TEMPLATE = """#!/bin/sh
# Generated by 'tig --shim'. Runs the VICAR tool this was invoked as.
tool=$(basename "$0")
if [ "$tool" = "{dispatcher}" ]; then
    if [ $# -eq 0 ]; then
        echo "usage: {dispatcher} <vicar_tool> [args...]" >&2
        exit 2
    fi
    tool=$1
    shift
fi
exec {tig} "$tool" "$@"
"""


def tig_executable() -> str:
    """Absolute path of the running tig, for the shims to call."""
    invoked = sys.argv[0] if sys.argv else ""
    if os.sep in invoked:
        return str(Path(invoked).resolve())
    return shutil.which(invoked or "tig") or "tig"


def default_shim_dir() -> Path:
    """Return the directory shims are written to when none is given."""
    data_home = os.environ.get("XDG_DATA_HOME")
    base = Path(data_home) if data_home else Path.home() / ".local" / "share"
    return base / "tig" / "shims"


def _shadows_host_command(tool: str, directory: Path) -> bool:
    """Whether a shim named ``tool`` would hide an existing host command."""
    found = shutil.which(tool)
    if found is None:
        return False
    return Path(found).parent.resolve() != directory.resolve()


def _stale_shims(directory: Path, dispatcher: Path) -> Iterable[Path]:
    """Existing symlinks in ``directory`` that point at the dispatcher."""
    target = os.path.realpath(dispatcher)
    for entry in directory.iterdir():
        if entry == dispatcher or not entry.is_symlink():
            continue
        if os.path.realpath(entry) == target:
            yield entry


def write_shims(
    directory: Path,
    tools: Iterable[str],
    tig: str,
    force: bool = False,
) -> Tuple[List[str], List[str]]:
    """Create one shim per tool in ``directory``.

    Tools whose name is already a command on the host PATH are skipped unless
    ``force``, so that putting the directory on PATH cannot shadow ``sort`` or
    ``patch``; those tools remain reachable as ``tig <tool>``. Names taken by a
    file this function did not generate are skipped in any case.

    Args:
        directory: Where to write the dispatcher and the per-tool symlinks
        tools: VICAR tool names
        tig: Path to the tig executable the shims should call
        force: Create shims even for names that exist on the host PATH

    Returns:
        The tool names written and the names skipped, both sorted.
    """
    directory.mkdir(parents=True, exist_ok=True)
    dispatcher = directory / DISPATCHER_NAME
    dispatcher.write_text(
        DISPATCHER_TEMPLATE.format(
            dispatcher=DISPATCHER_NAME, tig=shlex.quote(tig)
        )
    )
    dispatcher.chmod(
        dispatcher.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
    )

    for stale in list(_stale_shims(directory, dispatcher)):
        stale.unlink()

    written = []
    skipped = []
    for tool in sorted(set(tools)):
        if tool == DISPATCHER_NAME:
            continue
        if not force and _shadows_host_command(tool, directory):
            skipped.append(tool)
            continue
        link = directory / tool
        # Shims of ours were unlinked above, so anything left belongs to someone
        # else.
        if link.is_symlink() or link.exists():
            skipped.append(tool)
            continue
        link.symlink_to(DISPATCHER_NAME)
        written.append(tool)

    return written, skipped
