apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: tig-airflow
spec:
  type: ClusterIP
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: tig-airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:3.0
        ports:
        - containerPort: 4566
        env:
        - name: SERVICES
          value: "s3,sns,sqs"
        - name: SQS_ENDPOINT_STRATEGY
          value: "path"
        - name: DEBUG
          value: "1"
        - name: DATA_DIR
          value: "/tmp/localstack/data"
        - name: PERSISTENCE
          value: "0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
